### ISSUE TITLE
请问如何把hexo文件下的文件同步到github上面，就像你这个blog-archive一样

### ISSUE THREAD

**Issue by gaochen** [pinggod/blog-archive#17]
我在git add的时候提示有些文件已经有仓库了

**Comment by pinggod** [comment]
1. 在 GitHub 创建仓库，比如 `blog-archive`
2. 通过  `git clone` 将 `blog-archive` 拉取到本机
3. 将博客资源复制到本机的 `blog-archive`
4. 创建并完善 `.gitignore` 文件
5. 通过 `git add .; git commit -m 'blablabla'; git push` 命令操作推送到 GitHub 服务器
6. 以后可以在本机的 `blog-achive` 执行 Hexo 操作，需要备份时就是用 git 操作

上述未经实践，大体思路如此，如遇到问题，请附加详细信息。
