### ISSUE TITLE
HTML 语义化

### ISSUE THREAD

**Issue by pinggod** [pinggod/blog-archive#2]
# HTML 语义化

语义化标签是 HTML5 的新特性，也是现在前端开发的一项基本要求。作为整个页面的框架结构，合理、正确地使用 HTML 标签，才能达到稳健、可扩的需求。

关于语义化的好处，这里不多做介绍，包含但不限于：

- 结构清晰，具有良好的可读性
- 对屏幕阅读器等辅助工具友好
- 对搜索引擎友好
- 便于团队开发和维护

本文的要点在于提供一些语义化的实例，辨析常用标签的使用语境，规范开发行为。对于这些标签，简单地分成了两部分：结构相关的标签和文本相关的标签。每个开发者都有自己对标签的理解，所以，以下观点纯属个人学习和认知，欢迎交流。

## 语义化结构标签

![结构块示意图](http://www.html5jscss.com/pic/htmljscss/html5-layout.jpg)

为这篇文章查找资料时，我第一次看到了这张图，它很形象、很生动，通俗易懂地描述了语义化结构标签的用法的作用范围。少有的瑕疵仅在于图片的表达能力，还有一些细节无法展现在其中，容后解释。

语义化，即见名知意顾名思义。减少无意义的 `div`，使用具有表达作用的标签，让整体结构更加清晰，也减少了对类名的定义。

#### `<header>`

`<header>` 元素不计入内容结构，主要用作对区域内容的介绍说明，可以用于网页头部，也可以用于 `<article>` 标签中。

#### `<nav>`

`<nav>` 元素用来定义文档的主导航区域，其中的链接可以指向当前页面的关键部分，也可以指向其他页面。一般来说，页脚和其他区块的链接并不适用该标签。

#### `<article>`

`<article>` 元素用来包裹独立的内容，这种独立的内容应该具有标题和内容，是具有意义的完整内容，最常见的就是博客正文。

`<article>` 标签内允许嵌套 `<article>` 标签，内外标签中的内容应该具有相关性。

#### `<aside>`

`<aside>` 元素也可以定义与页面主题内容相关的内容，但这种相关性是松散的，或深或浅都无关紧要，常常用作页面的侧栏区域。另外，也可以用于广告、页脚导航等元素。

#### `<section>`

`<section>` 的字面意思是 `部分，小节，切片`，也就说，区别于 `<article>` 代表的完整内容，`<section>` 是独立的小节，需要有标题，但不要具有冗长的内容。当你犹豫不决使用哪种标签时，可以根据页面现有结构来判断，一般来说，`<article>` 这种主体内容并不需要太多，而 `<section>` 则可以有很多。

`<section>` 常常嵌套在 `<article>` 或 `<aside>` 标签中，用于组织局部内容，比如联系信息、文章动态等等。

此外，还有一个用于描述结构而无实际意义的标签 `<div>`，这三者的表义能力是按照 `<article>`、`<section>`、`<div>` 的顺序逐渐减弱的。总的来说，`<div>` 更适合为了效果不得不冗余的位置。

#### `<address>`

`<address>` 标签可以定义文档或作者的联系信息。如果该标签位于 `<body>` 中，则表示文档的关联性信息；如果该标签位于 `<article>` 之中，则表示文章的关联性信息。

虽然 `address` 有`地址`的意思，但却不能直接在 `<address>` 标签中填写联系信息，而是应该包裹进其他文本标签，比如 `<p>`。

#### `<footer>`

`<footer>` 元素主要用于 `<article>` 或页脚，不计入大纲结构，不用于划分内容结构。

## 语义化文本标签

在文本标签中，最容易混淆的就是 `<i>`、`<b>`、`<em>` 三个标签。首先，我们可以根据英文语义来辨析其中的差别：

- `<b>` (bold)，纯粹为了吸引注意力，不传达重要性，也不表示语态和语气；
- `<em>`(emphases)，强调内容中的重点；
- `<i>` (italian-handwriting)，该标签会调用意大利手写风格的字体，类似斜体样式，表示一段语气或语态不同的内容，或者表示与普通文字有所差异的特殊字体。鉴于中文字体中很少有斜体样式，所以该标签在中文中很少起到第二种作用，继而常常被用来引用字体图标。

在 HTML5 中，`<a>` 突破了嵌套限制，允许内部嵌套多个标签，直接利好就是扩大了鼠标事件的作用范围。唯一需要注意的是，不能在标签中嵌套表单。

`<figure>` 和 `<figcaption>` 标签包含一块独立的内容，如果该内容被移除，不应该影响周围内容。具体来说，可以用来包裹图片、图表、音频、代码段等。`<figcaption>` 用来给这段内容添加标题，而且只能存在 `<figure>` 标签内，位置随意。 

其他语义化文本标签的用法较为明确，详列如下：

|标签|用法|
|:--------:|-----------|
|code|程序代码|
|q|短引文|
|blockquote|长引文|
|pre|预格式文本|
|cite|引用的出处|
|abbr|缩写名词，在其 `title` 属性中给出术语全名|
|dfn|定义一个术语|
|br|定义一个换行符|

>如果只是实现换行效果，建议使用 `display` 属性将其块级化；`<br>` 标签更适合用于文本中换行。

## 小示例

下面这个示例来自 [《web 语义化》](http://www.cnblogs.com/dolphinX/p/3311588.html)一文，非常典型：

```html
<table>
	<tr>
		<td colspan="2">Student List</td>
	</tr>
	<tr>
		<td>Name</td>
		<td>Age</td>
	</tr>
	<tr>
		<td>Byron</td>
		<td>24</td>
	</tr>
	<tr>
		<td>Vincent</td>
		<td>25</td>
	</tr>
	<tr>
		<td>Casper</td>
		<td>27</td>
	</tr>
</table>
```

上面的表格结构差强人意，只能说浏览器渲染出来没问题，但对于搜索引擎来说，并不能正确理解其中的主次详略，也不利于后期维护。语义化后代码：

```html
<table>
	<caption>Student List</caption>
	<thead>
		<tr>
			<th>Name</th>
			<th>Age</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Byron</td>
			<td>24</td>
		</tr>
		<tr>
			<td>Vincent</td>
			<td>25</td>
		</tr>
		<tr>
			<td>Casper</td>
			<td>27</td>
		</tr>
	</tbody>
</table>
```

标题和内容一目了然，开发者和搜搜引擎都可以根据相应的标签了解到具体的结构层次，很赞。

###### 参考资料

- [语义化的HTML结构到底有什么好处？](http://www.css88.com/archives/1668)
- [《响应式 WEB 设计：HTML5 和 CSS3 实战》](http://book.douban.com/subject/20390374/)
- [HTML 标签参考手册](http://www.w3school.com.cn/tags/index.asp)
- [HTML 5 的革新 — 语义化标签（一）](http://www.html5jscss.com/html5-semantics-section.html)
- [HTML 5 的革新 — 语义化标签（二）](http://www.html5jscss.com/html5-semantics-rich.html)
- [《web 语义化》](http://www.cnblogs.com/dolphinX/p/3311588.html)

**Comment by hizoubin** [comment]
<footer>

<footer> 元素主要用于 <article> 或页脚，不计入大钢结构，不用于划分内容结构。

由个错别字 大纲结构

**Comment by hizoubin** [comment]
元素主要用于 或页脚，不计入大钢结构，不用于划分内容结构。
footer有个错别字 大纲结构
